backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "images/uploads"

collections:
  - name: "cake"
    label: "Cake"
    folder: "products"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
